apiVersion: v1
kind: ConfigMap
metadata:
  name: recipe-manager-api-config
  namespace: recipe-manager
  labels:
    app: recipe-manager
data:
  NODE_ENV: 'production'
  SERVER_PORT: '5000'
  CORS_ORIGINS: 'REPLACE_WITH_CORS_ORIGINS'
  DB_USER: 'REPLACE_WITH_RDS_USERNAME'
  DB_PORT: '5432'
  DB_HOST: 'REPLACE_WITH_RDS_ADDRESS'
  DB_NAME: 'REPLACE_WITH_RDS_DATABASE_NAME'
