# TODO instead of using plain Kubernetes secrets, consider the following
# alternatives to retrieve secrets from AWS Secrets Manager:
# 1. External Secrets Operator
#    - https://external-secrets.io/latest/
#    - https://github.com/external-secrets/external-secrets
# 2. sealed-secrets
#    - https://github.com/bitnami-labs/sealed-secrets
# 3. Secrets Store CSI Driver
#    - https://secrets-store-csi-driver.sigs.k8s.io/
#    - https://github.com/kubernetes-sigs/secrets-store-csi-driver
#    - https://github.com/aws/secrets-store-csi-driver-provider-aws

apiVersion: v1
kind: Secret
metadata:
  name: recipe-manager-api-secrets
  namespace: recipe-manager
  labels:
    app: recipe-manager
type: Opaque
stringData:
  DB_PASSWORD: 'REPLACE_WITH_RDS_PASSWORD'
  JWT_SECRET: 'REPLACE_WITH_JWT_SECRET'
  EMAIL_USER: 'REPLACE_WITH_EMAIL_USER'
  EMAIL_PASSWORD: 'REPLACE_WITH_EMAIL_PASSWORD'
