# TODO use External Secrets Operator to retrieve secrets from AWS Secrets Manager
# or sealed-secrets (https://github.com/bitnami-labs/sealed-secrets) instead of
# plain Kubernetes secrets.

apiVersion: v1
kind: Secret
metadata:
  name: recipe-manager-api-secrets
  namespace: recipe-manager
  labels:
    app: recipe-manager
type: Opaque
stringData:
  DB_PASSWORD: 'REPLACE_WITH_RDS_PASSWORD'
  JWT_SECRET: 'REPLACE_WITH_JWT_SECRET'
  EMAIL_USER: 'REPLACE_WITH_EMAIL_USER'
  EMAIL_PASSWORD: 'REPLACE_WITH_EMAIL_PASSWORD'
