# For Pod Identity
# The ServiceAccount can be created after the aws_eks_pod_identity_association
# resource, it just needs the name to match.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: recipe-manager-api
  namespace: recipe-manager
  labels:
    app: recipe-manager
