apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# Labels for all resources
labels:
  - pairs:
      environment: prod

patches:
  - path: ingress_patch.yaml
  - path: deployment_patch.yaml
